### ISSUE TITLE
issue after upgrading to v2.0.6

### ISSUE THREAD

**Issue by mahyarsat** [epicblockchain/epic-miner#2]
Hi,
My miner came with v2.0.5 today and I have update my sc200 firmware to v2.0.6 and now my miner seems to be acting up.
the hash rate stays at 0 MH/s, epic dashboard doesn't recognize the name of the device anymore and show it as undefined.
every few minutes all the info in columns turn to "error" in dashboard and few seconds later it turns back but uptime goes to 0 and hash rate stays at 0.
I can update the mining pool and wallet address and all shows successful message but COIN button is greyed out and can't be selected.
I tried reboot and recalibrate and it doesn't seem to help.

**Comment by cfilipescu** [comment]
@mahyarsat 

What mode are you running your miner?

Can you power down the miner and flash the SDcard using the following procedure:
https://github.com/epicblockchain/epic-miner#flashing-a-microsd-card-with-epic-image-sd-card-comes-preflashed-now

Use the *.img file to flash the sd card.

**Comment by mahyarsat** [comment]
I've tested both normal and efficiency mode no difference!
I had to go to office to have access to microSD and even doing that didn't change a thing. still getting error and rebooting every few minutes.
where can I find v2.0.5?

**Comment by mahyarsat** [comment]
I had another boxed miner which got unboxed today, I used the SD in that which was v2.0.5 and cloned it for my another miner so now both are on v2.0.5
now dashboard identify both miners with their names and right FW version. the problem is that now from time to time both of them go to error state again.
both are in efficiency mode and arguably running for much longer time than before (like 20 mins or so)

**Comment by cfilipescu** [comment]
Can you send a screenshot of the dashboard when the miners show up?
What is your ambient temperature? Is there any blockage 30cm in front or behind the miners?

**Comment by mahyarsat** [comment]
![sc200e](https://user-images.githubusercontent.com/27286692/129167574-ac9f8780-7aa3-47b6-9e48-5f476497e5e8.PNG)
there was blockage on 20cm behind the device and i removed it and seems that the second device is good for last 30 mins
but the first machine which had v2.0.6 and now v2.0.5 still ends up in undefined and return errors
![sc200](https://user-images.githubusercontent.com/27286692/129170803-30469835-c4cc-4d00-9cef-2c16282c828f.PNG)

**Comment by mahyarsat** [comment]
ok the other one started to restart as well, I have an air conditioner in my mining room and the miners didn't work long enough to get overheated.
also my workers name always change by itself and it seems it doesn't save it, this happens when device goes to error state and restart itself. also hash rate stays at zero !!!

**Comment by cfilipescu** [comment]
Are you sure the miner can access the internet and you don't have some firewall blocking it? 
Since the hash rate is 0 and the miner keeps rebooting. The miner reboots after a few minutes if it doesn't get any solutions because it can't access the outside network.

What is the format for the mining wallet that you used? 
Was it the following format: <sia_address>.<worker_name>

Can you take a screenshot of the "WALLET ADDRESS" tab after you select one of the miners?

**Comment by mahyarsat** [comment]
miners are restarting every 3-5 minutes now, I was suspecting the temperature so I increased the fan but no difference.
there shouldn't be a reason preventing them from internet, there is no firewall and they are getting IP from the router normally like other devices on the network.
if the miner doesn't restart for 15-20 minutes which happened when I turned on device this morning, it will show some Hash power but that goes down with restart as well.
about the wallet I am using Luxor pool and I tried different combinations.
wallet address + worker name
Luxor username + worker name
I am not sure about this part to be honest, when trying to setup Luxor it gives me my username.Mickey for example and no sign of wallet address there but in dashboard wallet address seems to be default one

![wallet](https://user-images.githubusercontent.com/27286692/129194267-ed4dd437-02c9-429d-a42b-70d1ad0f162b.PNG)
![wallet2](https://user-images.githubusercontent.com/27286692/129194268-2d88d9fa-0835-44c9-bc97-f25db8b660d8.PNG)

**Comment by cfilipescu** [comment]
Are you comfortable ssh-ing into the miner right after it reboots?
ssh root@192.168.32.8
password is the same as the dashboard

and run "tmux a"

once in tmux scroll to the top and see if you can capture the beginning of the log and the bottom

**Comment by gazelleryanwalker** [comment]
my epic miner turns on for 3 seconds and then shuts off like some safeguard
or something is shutting it down,, any ideas how to fix this, i havent been
able to run it in 3 weeks?
Cheers,

Ryan Walker
Founder/CEO
gazelleinteractive.com

p: 888.814.8599
m: 858.220.9410
e: ***@***.***
a. Delray Beach, Fl
     *Online Meeting Now*
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW3HbfJ-4fdJS3W1LDkqX41ZPq8W3XWHRL3_SMKM4Q2Bh1&si=8000000005356870&pi=0defbb8d-1be9-4843-aab1-14c7702c0e91>

[image: facebook]
<https://www.facebook.com/RyanWalkerGazelleInteractive> [image:
linkedin]
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lyz993N-SFpW3ZY6xN41YyllF3z8p29mLcC1&si=8000000005356870&pi=0defbb8d-1be9-4843-aab1-14c7702c0e91>
[image:
map]
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW3NBCyQ3P0nZpW3zkYFC3ZVczqW4fGCnk3Fdy8lF3JNBVvPc-S1&si=8000000005356870&pi=0defbb8d-1be9-4843-aab1-14c7702c0e91>
  [image: instagram]
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW4mKLS-3T1lc2W3zb2N33_qTryW3_rhPt4cQgwpw3zd6x548Y2&si=8000000005356870&pi=0defbb8d-1be9-4843-aab1-14c7702c0e91>

**Comment by cfilipescu** [comment]
@gazelleryanwalker What power supply do you have? And what is the outlet voltage?
When the miner boots up the first time it pulls about 1000W.

Can you take a video of the boot process up to the point of failure?

**Comment by gazelleryanwalker** [comment]
i have the powersupply that i bought thru epic when i bought the miner,,,
it was running fine for 5 months and now is just dying
Cheers,

Ryan Walker
Founder/CEO
gazelleinteractive.com

p: 888.814.8599
m: 858.220.9410
e: ***@***.***
a. Delray Beach, Fl
     *Online Meeting Now*
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW3HbfJ-4fdJS3W1LDkqX41ZPq8W3XWHRL3_SMKM4Q2Bh1&si=8000000005356870&pi=d61c5b91-9739-4604-e222-27da81c77219>

[image: facebook]
<https://www.facebook.com/RyanWalkerGazelleInteractive> [image:
linkedin]
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lyz993N-SFpW3ZY6xN41YyllF3z8p29mLcC1&si=8000000005356870&pi=d61c5b91-9739-4604-e222-27da81c77219>
[image:
map]
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW3NBCyQ3P0nZpW3zkYFC3ZVczqW4fGCnk3Fdy8lF3JNBVvPc-S1&si=8000000005356870&pi=d61c5b91-9739-4604-e222-27da81c77219>
  [image: instagram]
<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8bGpXVW5xtBw22zGCwVN8Jbw_8QsRtKVp0Vg63Lrf_dW16gGFj84SmL1101?te=W3R5hFj4cm2zwW4mKLS-3T1lc2W3zb2N33_qTryW3_rhPt4cQgwpw3zd6x548Y2&si=8000000005356870&pi=d61c5b91-9739-4604-e222-27da81c77219>

**Comment by cfilipescu** [comment]
@gazelleryanwalker please contact support at support@epicblockchain.io along with the video showing the problem

**Comment by mahyarsat** [comment]
so the output at the gives an error and it says "haven't received a new work, Exiting ..."
and then the restart happens and SSH is gone!
after restart there is another Error too. Error reading messages from stream Connection Error, Broken pipe, bad error

![ssh](https://user-images.githubusercontent.com/27286692/129202177-ded22c9a-17ab-43a6-bcab-cfdf800f38b8.PNG)

![ssh2](https://user-images.githubusercontent.com/27286692/129202735-4526432d-f4b2-4144-95fa-6668770bd8ea.PNG)

**Comment by cfilipescu** [comment]
The connection to the mining pool seems to be broken, it connects initially but loses the connection. 
Two things you can try:
- try mining to a different pool: maybe siamining
- reflash reflash the sdcard with the 2.0.6 image and let it run for 15 min, that will mine to a default address and it will tell us if it's a configuration problem or a pool connection problem (if the hashrate shows up as nonzero it's a config problem)

**Comment by mahyarsat** [comment]
it seems it was the pool issue all the time and switching it immediately fixed the problem. thanks!
